
CREATE DATABASE 'hidrostal';
USE hidrostal;
CREATE TABLE `planos` (
  `id_plano` INT AUTO_INCREMENT PRIMARY KEY,
  `anio` INT NOT NULL,
  `mes` VARCHAR(20) NOT NULL,
  `descripcion` VARCHAR(255) NOT NULL,
  `num_plano` VARCHAR(64) NOT NULL,
  `size` VARCHAR(4) NOT NULL,
  `version` VARCHAR(16) NOT NULL,
  `dibujante` VARCHAR(120) NOT NULL,
  `dibujado_en` VARCHAR(50) NOT NULL,
  `archivo_plano` LONGBLOB NOT NULL,
  `created_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `updated_at` DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4;